name: codebase
channels:
  - defaults
dependencies:
  - abseil-cpp
  - aiohttp
  - aiosignal
  - arrow-cpp
  - async-timeout
  - attrs
  - aws-c-common
  - aws-c-event-stream
  - aws-checksums
  - aws-sdk-cpp
  - blas
  - boost-cpp
  - bottleneck
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - certifi
  - cffi
  - click
  - colorama
  - cryptography
  - datasets
  - dill
  - exceptiongroup
  - ffmpeg
  - flask
  - flask_cors
  - frozenlist
  - fsspec
  - future
  - gflags
  - glog
  - greenlet
  - huggingface_hub
  - idna
  - iniconfig
  - intel-openmp
  - itsdangerous
  - jinja2
  - joblib
  - libboost
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcurl
  - libffi
  - libprotobuf
  - libssh2
  - libthrift
  - libuv
  - lz4-c
  - markupsafe
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - multidict
  - multiprocess
  - ninja
  - ninja-base
  - numexpr
  - numpy
  - numpy-base
  - openssl
  - orc
  - packaging
  - pandas
  - pip
  - pluggy
  - pyarrow
  - pycparser
  - pyopenssl
  - pysocks
  - pytest
  - python
  - python-dateutil
  - python-xxhash
  - pytorch
  - pytz
  - pyyaml
  - re2
  - regex
  - responses
  - sacremoses
  - sentencepiece
  - setuptools
  - six
  - snappy
  - sqlalchemy
  - sqlite
  - tbb
  - tk
  - tokenizers
  - tomli
  - tqdm
  - transformers
  - typing-extensions
  - typing_extensions
  - tzdata
  - utf8proc
  - vc
  - vs2015_runtime
  - werkzeug
  - wheel
  - win_inet_pton
  - xxhash
  - xz
  - yaml
  - yarl
  - zlib
  - zstd
  - pip:
      - absl-py
      - antlr4-python3-runtime
      - audioread
      - chardet
      - charset-normalizer
      - comtypes
      - contourpy
      - cycler
      - dtwalign
      - editdistance
      - eng-to-ipa
      - epitran
      - example
      - filelock
      - fonttools
      - kiwisolver
      - llvmlite
      - marisa-trie
      - matplotlib
      - mpmath
      - munkres
      - networkx
      - numba
      - omegaconf
      - ortools
      - panphon
      - pillow
      - playsound
      - protobuf
      - pydub
      - pyparsing
      - pypiwin32
      - pyttsx3
      - pywin32
      - requests
      - scipy
      - seaborn
      - soundfile
      - speechrecognition
      - sympy
      - torch
      - torchaudio
      - unicodecsv
      - urllib3
